name: Build

on:
  push:
    tags:
      - v*.**
  workflow_dispatch:
    inputs:
      package:
        description: '软件包名称'
        required: true
        default: 'luci-app-mproxy'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Build OpenWrt package
        uses: openwrt/package-build-action@v1
        with:
          package-name: ${{ github.event.inputs.package || 'luci-app-mproxy' }}
          # 使用支持你架构的SDK
          openwrt-version: 23.05
          target: mvebu/cortexa9
          arch: arm_cortex-a9

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: "*.ipk"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.ipk"
          token: ${{ secrets.GITHUB_TOKEN }}
