name: Build

on:
  push:
    tags:
      - v*.**
  workflow_dispatch:
    inputs:
      arch:
        description: '目标架构'
        required: true
        default: 'arm_cortex-a9'
        type: choice
        options:
          - arm_cortex-a9
      sdk:
        description: 'OpenWrt版本'
        required: true
        default: 'openwrt-22.03'
        type: choice
        options:
          - openwrt-22.03

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm_cortex-a9
        sdk:
          - openwrt-22.03

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@go1.20
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-mproxy
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          if-no-files-found: ignore

      - name: Set Release Tag
        id: release_tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "tag=manual-build-${{ github.run_number }}" >> $GITHUB_OUTPUT
            echo "name=Manual Build #${{ github.run_number }} (${{ github.event.inputs.arch }}-${{ github.event.inputs.sdk }})" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.release_tag.outputs.name }}
          tag: ${{ steps.release_tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
